/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.CadUrna;
import eleicoes.recursos.*;

/**
 *
 * @author 0768170
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArq = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuUrna = new javax.swing.JMenu();
        mnuCad = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        mnuRel = new javax.swing.JMenu();
        mnuListUrnas = new javax.swing.JMenuItem();
        mnuPesqSituacao = new javax.swing.JMenuItem();
        mnuPesqCidadeUf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuArq.setText("Arquivo");

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuArq.add(mnuSair);

        jMenuBar1.add(mnuArq);

        mnuUrna.setText("Urna");

        mnuCad.setText("Cadastrar");
        mnuCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadActionPerformed(evt);
            }
        });
        mnuUrna.add(mnuCad);

        mnuExcluir.setText("Excluir");
        mnuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExcluirActionPerformed(evt);
            }
        });
        mnuUrna.add(mnuExcluir);

        jMenuBar1.add(mnuUrna);

        mnuRel.setText("Relatórios");

        mnuListUrnas.setText("Listar todas as Urnas");
        mnuListUrnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListUrnasActionPerformed(evt);
            }
        });
        mnuRel.add(mnuListUrnas);

        mnuPesqSituacao.setText("Pesquisar por situação");
        mnuPesqSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqSituacaoActionPerformed(evt);
            }
        });
        mnuRel.add(mnuPesqSituacao);

        mnuPesqCidadeUf.setText("Pesquisar por Cidade/UF");
        mnuPesqCidadeUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqCidadeUfActionPerformed(evt);
            }
        });
        mnuRel.add(mnuPesqCidadeUf);

        jMenuBar1.add(mnuRel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuListUrnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListUrnasActionPerformed
        new ListUrnas().setVisible(true);
    }//GEN-LAST:event_mnuListUrnasActionPerformed

    private void mnuCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadActionPerformed
        new CadUrna().setVisible(true);
    }//GEN-LAST:event_mnuCadActionPerformed

    private void mnuPesqCidadeUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqCidadeUfActionPerformed
        // TODO add your handling code here:
        new selLoc().setVisible(true);
    }//GEN-LAST:event_mnuPesqCidadeUfActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExcluirActionPerformed
        new ExcUrna().setVisible(true);
    }//GEN-LAST:event_mnuExcluirActionPerformed

    private void mnuPesqSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqSituacaoActionPerformed
      new selSit().setVisible(true);
    }//GEN-LAST:event_mnuPesqSituacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuArq;
    private javax.swing.JMenuItem mnuCad;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JMenuItem mnuListUrnas;
    private javax.swing.JMenuItem mnuPesqCidadeUf;
    private javax.swing.JMenuItem mnuPesqSituacao;
    private javax.swing.JMenu mnuRel;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuUrna;
    // End of variables declaration//GEN-END:variables
}
